### ISSUE TITLE
Segfault on domain 

### ISSUE THREAD

**Issue by ronwalf** [miquelramirez/LAPKT-public#12]
I have a relatively simple domain and suite of problems that BFS segfaults on.  FF-X also segfaults on it (and probably FF, too), but FD-derived planners don't.
[domain.pddl.txt](https://github.com/miquelramirez/LAPKT-public/files/43479/domain.pddl.txt)
[problem.pddl.txt](https://github.com/miquelramirez/LAPKT-public/files/43480/problem.pddl.txt)

Given the common segfault, it's probably in the libff code.  You may need to bump MAX_ARITY in libff/ff.h to 8 or so get it to parse.

**Comment by nirlipo** [comment]
Hi Ron,

The planner BFS_f using FD parser solves the problem. It's located in planners/bfs_f folder.

Increasing the MAX_ARITY causes a segfault in the reachability_analysis performed by FF parser. 

The issue is that the number of negated literal goes out of bound, more than max_int value.

https://github.com/miquelramirez/LAPKT-public/blob/master/external/libff/inst_final.c#L148

and the salloc fails. If you change it to long long is too memory intensive. I rather try to decrease either the num_constants in the pddl and the arity. But, the version that uses the FD parser works fine with the attached files.

Regards,

Nir

**Comment by ronwalf** [comment]
Thanks, that's quite informative!

As background, these are automatically translated problems from an HTN formalism, so I'm loathe to change their descriptions more than necessary.  I have a technique to compile these particular predicates into sets of smaller predicates, but it's likely to play havoc with most heuristics (certainly both h^FF and landmark analysis).

**Comment by miquelramirez** [comment]
Hello Ron,

I think I have a notion of what you're tyring to achieve, and I think that propositional STRIPS just lacks the expressive power to represent in a compact way those HTN hierarchies. One of the reasons why my ongoing work on PR is a bit stuck is that any truly interesting plan library/task network when compiled to STRIPS - even if we're missing some plans during the compilation - just blows up in your face.

I would suggest that you look into Guillem Frances' implementation of Functional Strips

https://bitbucket.org/gfrances/fs0/overview

some of the stuff Guillem has already done and has on the pipeline, would go a very long way to provide you with much better tool support.

Thanks for the interest,

Miquel.

**Comment by ronwalf** [comment]
Hi Miquel!

Thanks for the pointer. If my skimming of functional STRIPS is right, it would allow arbitrary translation of HTNs and ConGolog to a functional PDDL.  However, while I agree that STRIPS isn't expressive enough for all HTN problems, we're actually getting decent results on a number of benchmark problems using off-the-shelf classical planners.    

You can play around with an older version of our code here: 
https://github.com/ronwalf/HTN-Translation
It can automatically translate any tail-recursive or acyclic HTN problem.  Although the bounds on the translation can theoretically be quite large, the problems we were tried had relatively reasonable bounds.

This specific problem also isn't directly related to the hierarchy, but rather having massive numbers of variables in the methods and task names.  Since traditional HTN planners don't fully ground the domain before planning, this never bothered them.

**Comment by miquelramirez** [comment]
Thanks for that link Ron, it will come in handy :)

Regarding Func Strips, of specific interest I think will be the notion of nested fluents (yes, it supports nesting functions in the heuristic and the execution model) and other stuff... I'd suggest you to write to him about this topic - he's very keen on showcasing the expressive power (and efficiency) of Functional Strips as implemented on FS0.
